### ISSUE TITLE
Height of element

### ISSUE THREAD

**Issue by RouberR** [AdamLee321/react-native-sortable-dynamic#4]
Hi, useful library, but tell me, can I change the height of an element?

**Comment by AdamLee321** [comment]
Hi, could you give me a specific use case?

**Comment by RouberR** [comment]
@AdamLee321 I want to make an element vertical and horizontal. For example, make 3 separate lists with different elements


  SQUARE: {
    width: 171,
    height: 171,
  },
  HORIZONTAL: {
    width: 358,
    height: 171,
  },
  VERTICAL: {
    width: 171,
    height: 372,
  },

{!!widgets.filter(i => i.position === 'SQUARE').length && (
        <SortableView
          config={{ MARGIN: 10, COL: 2 }}
          data={widgets.filter(i => i.position === 'SQUARE')}
          editing={true}
          onDragEnd={positions => console.log(positions)}
          renderItem={renderWidget}
          itemStyle={{height:171}}
        />
      )}

 {!!widgets.filter(i => i.position === 'VERTICAL').length && (
        <SortableView
          config={{ COL: 2 }}
          data={widgets.filter(i => i.position === 'VERTICAL')}
          editing={true}
          onDragEnd={positions => console.log(positions)}
          renderItem={renderWidget}
            itemStyle={{height:372}}
        />
      )}


![image](https://github.com/user-attachments/assets/ca85a903-e4f6-447a-8623-dfb10c41f435)

![image](https://github.com/user-attachments/assets/48cddef6-7408-4956-89c4-6d67a377db84)

**Comment by RouberR** [comment]
@AdamLee321 I wanted to combine square, vertical and horizontal elements into one block and move them between each other. But I couldn't make it work properly. I started looking for libraries, react-native-drag-sort works very badly on android. So I want to achieve this result at least by dividing the elements into blocks with different element sizes ))

**Comment by AdamLee321** [comment]
Unfortunately, the way this code works relies on each item having the same height and width. I would advise forking this library and updating it to suit your specific use case. 

I plan to allow for dynamic heights in the future but don't have time to work adding this right now. Feel free to make a PR if you manage to get it working. Sorry I couldn't be more help.

**Comment by AdamLee321** [comment]
The item height and width are constants at the moment and would require only code minor code changes to get it working as you intend it to. If you are stuck feel free to ask more questions. 

https://github.com/AdamLee321/react-native-sortable-dynamic/blob/0004103df440b570a1393a9fc88a6366710794f5/src/SortableItem.js#L39
